<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RANJIT" failures="1" tests="8" name="cucumberOptions.TestRunner" time="69.159" errors="0" timestamp="2023-10-02T21:53:49 IST" skipped="0">
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="28.722"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="4.397"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="4.916"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="3.332"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="4.141"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="8.988"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="9.158"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="5.505">
    <failure message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinations.LoginPageSteps.user_is_logged_in(LoginPageSteps.java:97)
at âœ½.user is logged in(file:///C:/Users/RANJIT/eclipse-workspace/BddFrameWork/src/test/java/featureLayer/Login.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- cucumberOptions.TestRunner -->
